### ISSUE TITLE
Create per experiment schedulers

### ISSUE THREAD

**Issue by recap** [obeliss-nlesc/otree-waiting-room#15]
What's the task
Create modularized schedulers to be loaded dynamically by the webservice at bootup.

Why we're doing it
We foresee that different experiments will need different ways to schedule users to servers/experiments. For this reason it will save time to already create a plugin architecture for loading schedulers.

Steps we'll take
Create a scheduler interface class and a  simple GAT (group by arrival time) implementation of it with two parameters ‘min_group_size' and 'max_group_size'.  Think of which methods the interface needs to expose.

**Comment by ewan-escience** [comment]
Closed by #35
