### ISSUE TITLE
Detect re-entrant users and map them to the same server

### ISSUE THREAD

**Issue by recap** [obeliss-nlesc/otree-waiting-room#21]
A user can hit the waiting-room multiple times

- if already queued and waiting do nothing and return the waiting room page.
- if was redirected to a server, try to redirect again to the same server. If server is down then requeue the user.
- if user had finished experiment, return a 'finished' html page.

**Comment by ewan-escience** [comment]
> if already queued and waiting do nothing and return the waiting room page.

This is already the case, right? A user can only enter with a token, and we store the state of those users if they weren't redirected to an oTree server yet.
